export const UserData = [
  {
    id: 1,
    year: 2020,
    userGain: 80000,
    userLost: 823,
  },
  {
    id: 2,
    year: 2021,
    userGain: 70000,
    userLost: 345,
  },
  {
    id: 3,
    year: 2022,
    userGain: 78888,
    userLost: 555,
  },
  {
    id: 4,
    year: 2023,
    userGain: 60000,
    userLost: 4555,
  },
  {
    id: 5,
    year: 2024,
    userGain: 63000,
    userLost: 234,
  },
];

export const database = [
  {
    Id: "EXP-1047",
    vendor: "Innovation Inc",
    customer: "Expense related to",
    email: "johndoe@gmail.com",
    products: 2,
    total: 250,
    status: "Suspended",
    payment: "paid",
    commission: "$66.70",
    orderDate: "2024-01-15",
    category: "Electronics",
  },
  {
    Id: "EXP-1003",
    vendor: "Novel Nook",
    customer: "Expense related to",
    email: "janesmith@gmail.com",
    products: 2,
    total: 913.00,
    status: "pending",
    payment: "pending",
    commission: "91.00",
    orderDate: "2022-03-15",
    category: "Automative",
  },
  {
    Id: "EXP-1034",
    vendor: "Top Treasury",
    customer: "Expense related to",
    email: "johndoe@gmail.com",
    products: 4,
    total: 2500,
    status: "Rejected",
    payment: "failed",
    commission: "$152.00",
    orderDate: "2025-09-15",
    category: "Fashion",
  },
  {
    Id: "EXP-1038",
    vendor: "Car Care Plus",
    customer: "Expense related to",
    email: "samsmith@gmail.com",
    products: 2,
    total: 5980.00,
    status: "Pending",
    payment: "pending",
    commission: "$161.00",
    orderDate: "2026-01-2",
    category: "Home & Garden",
  },
  {
    Id: "EXP-1035",
    vendor: "Glamour Shop",
    customer: "Expense related to",
    email: "alexjohn@gmail.com",
    products: 8,
    total: 8500,
    status: "suspended",
    payment: "refunded",
    commission: "$162.00",
    orderDate: "2025-07-15",
    category: "Beauty",
  },
  {
    Id: "EXP-1045",
    vendor: "Kiddie Kingdom",
    customer: "Expense related to",
    email: "mariagarcia@gmail.com",
    products: 1,
    total: 150,
    status: "Pending",
    payment: "paid",
    commission: "$169.00",
    orderDate: "2023-02-3",
    category: "Books",
  },
  {
    Id: "EXP-1023",
    vendor: "Makeup Maven",
    customer: "Expense related to",
    email: "lindabrown@gmail.com",
    products: 3,
    total: 750,
    status: "Rejected",
    payment: "failed",
    commission: "$220.90",
    orderDate: "2025-12-2",
    category: "Toys",
  },
  {
    Id: "EXP-1024",
    vendor: "Skin Savvy",
    customer: "Expense related to",
    email: "robertdavis@gmail.com",
    products: 5,
    total: 1250,
    status: "Rejected",
    payment: "paid",
    commission: "$174.40",
    orderDate: "2024-12-31",
    category: "Sports",
  },
  {
    Id: "EXP-1004",
    vendor: "Wardrobe Wonders",
    customer: "Expense related to",
    email: "johndoe@gmail.com",
    products: 2,
    total: 250,
    status: "Suspended",
    payment: "paid",
    commission: "$182.87",
    orderDate: "2025-09-15",
    category: "Software",
  },
  {
    Id: "EXP-1032",
    vendor: "Fun Factory",
    customer: "Expense related to",
    email: "janesmith@gmail.com",
    products: 2,
    total: 250,
    status: "Suspended",
    payment: "pending",
    commission: "$182.87",
    orderDate: "2025-06-17",
    category: "Electronics",
  },
  {
    Id: "EXP-1036",
    vendor: "Garden Paradise",
    customer: "Expense related to",
    email: "johndoe@gmail.com",
    products: 4,
    total: 2500,
    status: "Pending",
    payment: "failed",
    commission: "$182.87",
    orderDate: "2024-09-15",
    category: "Automative",
  },
  {
    Id: "EXP-1049",
    vendor: "Beauty Bliss",
    customer: "Expense related to",
    email: "samsmith@gmail.com",
    products: 2,
    total: 5980,
    status: "Rejected",
    payment: "pending",
    commission: "$304.87",
    orderDate: "2024-09-15",
    category: "Toys",
  },
  {
    Id: "EXP-1029",
    vendor: "Fitness First",
    customer: "Expense related to",
    email: "alexjohn@gmail.com",
    products: 8,
    total: 8500,
    status: "Pending",
    payment: "refunded",
    commission: "$89.87",
    orderDate: "2024-09-15",
    category: "Books",
  },
  {
    Id: "EXP-1021",
    vendor: "Chic Boutique",
    customer: "Expense related to",
    email: "mariagarcia@gmail.com",
    products: 1,
    total: 150,
    status: "Suspended",
    payment: "paid",
    commission: "$243.87",
    orderDate: "2024-09-15",
    category: "Home & Garden",
  },
  {
    Id: "EXP-1104",
    vendor: "Auto Parts Pro",
    customer: "Expense related to",
    email: "lindabrown@gmail.com",
    products: 3,
    total: 750,
    status: "pending",
    payment: "failed",
    commission: "$82.87",
    orderDate: "2025-07-15",
    category: "Electronics",
  },
  {
    Id: "EXP-1114",
    vendor: "Cosmetic Corner",
    customer: "Expense related to",
    email: "robertdavis@gmail.com",
    products: 5,
    total: 1250,
    status: "Pending",
    payment: "paid",
    commission: "$382.87",
    orderDate: "2025-03-5",
    category: "Electronics",
  },
];

export const ExpenseData = [
  { month: "Jan", expense: 2400 },
  { month: "Feb", expense: 4500 },
  { month: "Mar", expense: 1420 },
  { month: "Apr", expense: 2120 },
  { month: "May", expense: 3140 },
  { month: "Jun", expense: 9400 },
  { month: "Jul", expense: 9100 },
  { month: "Aug", expense: 6052 },
  { month: "Sept",expense: 2765 },
  { month: "Oct", expense: 11000 },
  { month: "Nov", expense: 12000 },
  { month: "Dec", expense: 2800 },
];


export const CategoryData = [
  {
    category: "Electronics",
    expense: 89500,
  },
  {
    category: "Accessories",
    expense: 3520000,
  },
  {
    category: "Software",
    expense: 2112000,
  },
  {
    category: "Home & Garden",
    expense: 333210,
  },
  {
    category: "Toys",
    expense: 89500,
  },
  {
    category: "Books",
    expense: 35200,
  },
  {
    category: "Fashion",
    expense: 211200,
  },
  {
    category: "Beauty",
    expense: 230321,
    
  },
  {
    category: "Sports",
    expense: 35200,
    
  },
];
