 export const product_database = [
    {
      id: 1,
      name: "Wireless Headphones Pro",
      category: "Electronics",
      sales: 1250,
      revenue: 124500,
      stock: 45,
      trend: "+15%",
    },
    {
      id: 2,
      name: "Smart Watch Series X",
      category: "Electronics",
      sales: 980,
      revenue: 196000,
      stock: 23,
      trend: "+22%",
    },
    {
      id: 3,
      name: "Laptop Stand Aluminum",
      category: "Furniture",
      sales: 756,
      revenue: 37800,
      stock: 120,
      trend: "+8%",
    },
    {
      id: 4,
      name: "USB-C Hub 7-in-1",
      category: "Furniture",
      sales: 654,
      revenue: 32700,
      stock: 5,
      trend: "-3%",
    },
    {
      id: 5,
      name: "Gaming Mouse RGB",
      category: "Electronics",
      sales: 543,
      revenue: 27150,
      stock: 89,
      trend: "+12%",
    },
    {
      id: 6,
      name: "Mechanical Keyboard",
      category: "Electronics",
      sales: 432,
      revenue: 64800,
      stock: 34,
      trend: "+5%",
    },
    {
      id: 7,
      name: "Phone Case Premium",
      category: "Furniture",
      sales: 398,
      revenue: 11940,
      stock: 2,
      trend: "-8%",
    },
    {
      id: 8,
      name: "Bluetooth Speaker",
      category: "Electronics",
      sales: 387,
      revenue: 38700,
      stock: 67,
      trend: "+18%",
    },
    {
      id: 9,
      name: "Webcam HD 1080p",
      category: "Electronics",
      sales: 321,
      revenue: 28890,
      stock: 45,
      trend: "+10%",
    },
    {
      id: 10,
      name: "Monitor Stand Wood",
      category: "Furniture",
      sales: 298,
      revenue: 17880,
      stock: 78,
      trend: "+6%",
    },
    {
      id: 11,
      name: "Wireless Headphones Pro",
      category: "Electronics",
      sales: 1250,
      revenue: 124500,
      stock: 45,
      trend: "+15%",
    },
    {
      id: 12,
      name: "Smart Watch Series X",
      category: "Electronics",
      sales: 980,
      revenue: 196000,
      stock: 23,
      trend: "+22%",
    },
    {
      id: 13,
      name: "Laptop Stand Aluminum",
      category: "Furniture",
      sales: 756,
      revenue: 37800,
      stock: 120,
      trend: "+8%",
    },
    {
      id: 14,
      name: "USB-C Hub 7-in-1",
      category: "Furniture",
      sales: 654,
      revenue: 32700,
      stock: 5,
      trend: "-3%",
    },
    {
      id: 15,
      name: "Gaming Mouse RGB",
      category: "Electronics",
      sales: 543,
      revenue: 27150,
      stock: 89,
      trend: "+12%",
    },
    {
      id: 16,
      name: "Mechanical Keyboard",
      category: "Electronics",
      sales: 432,
      revenue: 64800,
      stock: 34,
      trend: "+5%",
    },
    {
      id: 17,
      name: "Phone Case Premium",
      category: "Furniture",
      sales: 398,
      revenue: 11940,
      stock: 2,
      trend: "-8%",
    },
    {
      id: 18,
      name: "Bluetooth Speaker",
      category: "Electronics",
      sales: 387,
      revenue: 38700,
      stock: 67,
      trend: "+18%",
    },
    {
      id: 19,
      name: "Webcam HD 1080p",
      category: "Electronics",
      sales: 321,
      revenue: 28890,
      stock: 45,
      trend: "+10%",
    },
    {
      id: 20,
      name: "Monitor Stand Wood",
      category: "Furniture",
      sales: 298,
      revenue: 17880,
      stock: 78,
      trend: "+6%",
    },
    {
      id: 21,
      name: "Monitor Stand Wood",
      category: "Furniture",
      sales: 298,
      revenue: 17880,
      stock: 78,
      trend: "+6%",
    },
  ];