export const MarketData = [
  { region: "North America", sales: 58320, percentage: 80, customers: 620 },
  { region: "Europe", sales: 43746, percentage: 5, customers: 485 },
  { region: "Asia", sales: 29164, percentage: 70, customers: 312 },
  { region: "Others", sales: 14590, percentage: 99, customers: 130 },
];

export const CategoryData = [
  {
    category: "Electronics",
    sales: 89500,
    percentage: 61.4,
    product: 23,
    productSold: 1111,
    revenue: 100000,
  },
  {
    category: "Accessories",
    sales: 3520000,
    percentage: 24.1,
    product: 23,
    productSold: 1111,
    revenue: 100000,
  },
  {
    category: "Software",
    sales: 2112000,
    percentage: 14.5,
    product: 26,
    productSold: 2333,
    revenue: 230000,
  },
  {
    category: "Home & Garden",
    sales: 333210,
    percentage: 45,
    product: 21,
    productSold: 111,
    revenue: 10000,
  },
  {
    category: "Toys",
    sales: 89500,
    percentage: 61.4,
    product: 23,
    productSold: 411,
    revenue: 62000,
  },
  {
    category: "Books",
    sales: 35200,
    percentage: 24.1,
    product: 7,
    productSold: 111,
    revenue: 10000,
  },
  {
    category: "Fashion",
    sales: 211200,
    percentage: 14.5,
    product: 13,
    productSold: 911,
    revenue: 87000,
  },
  {
    category: "Beauty",
    sales: 230321,
    percentage: 45,
    product: 23,
    productSold: 610,
    revenue: 90000,
  },
  {
    category: "Sports",
    sales: 35200,
    percentage: 24.1,
    product: 23,
    productSold: 711,
    revenue: 20000,
  },
];

export const monthlyTrend = [
  { month: "Jan", sales: "98000", customers: 850 },
  { month: "Feb", sales: "105000", customers: 920 },
  { month: "Mar", sales: "1000", customers: 980 },
  { month: "Apr", sales: "290000", customers: 1050 },
  { month: "May", sales: "132000", customers: 1150 },
  { month: "Jun", sales: "145820", customers: 1247 },
  { month: "July", sales: "8000", customers: 850 },
  { month: "Aug", sales: "105000", customers: 920 },
  { month: "Sept", sales: "11200", customers: 980 },
  { month: "Oct", sales: "78000", customers: 1050 },
  { month: "Nov", sales: "152000", customers: 1150 },
  { month: "Dec", sales: "125820", customers: 1247 },
];

export const customerDemographics = [
  { ageGroup: " 18-24 ", percentage: 18, count: 280 },
  { ageGroup: "25-34", percentage: 35, count: 545 },
  { ageGroup: "35-44", percentage: 28, count: 436 },
  { ageGroup: "45-54", percentage: 12, count: 187 },
  { ageGroup: "55+", percentage: 7, count: 109 },
];

export const VendorData = [
  {
    vendorName: "TechHub Store",
    owners: "Michael owen",
    totalSales: "$15,000",
    product: 25,
    productsSold: 120,
    percentage: 60,
    rating: 4.5,
    status: "Active",
    categoris: "Electronics",
  },
  {
    vendorName: "Gadget World",
    owners: "Sarah Lee",
    totalSales: "$12,500",
    product: 12,
    productsSold: 95,
    percentage: 45,
    rating: 4.2,
    status: "Active",
    categoris: "Accessories",
  },
  {
    vendorName: "SoftSolutions",
    owners: "David Kim",
    totalSales: "$9,800",
    product: 7,
    productsSold: 80,
    percentage: 38,
    rating: 4.0,
    status: "Inactive",
    categoris: "Software",
  },
  {
    vendorName: "Device Depot",
    owners: "Emily Chen",
    totalSales: "$11,200",
    product: 15,
    productsSold: 110,
    percentage: 40,
    rating: 4.3,
    status: "Active",
    categoris: "Fashion",
  },
  {
    vendorName: "Accessory Alley",
    owners: "James Brown",
    totalSales: "$8,600",
    product: 5,
    productsSold: 70,
    percentage: 30,
    rating: 4.1,
    status: "Banned",
    categoris: "Home & Garden",
  },
  {
    vendorName: "CodeCrafters",
    owners: "Olivia Davis",
    totalSales: "$10,400",
    product: 9,
    productsSold: 85,
    percentage: 39,
    rating: 4.4,
    status: "Active",
    categoris: "Beauty",
  },
  {
    vendorName: "Gizmo Galaxy",
    owners: "Liam Wilson",
    totalSales: "$13,300",
    product: 25,
    productsSold: 105,
    percentage: 44,
    rating: 4.6,
    status: "Active",
    categoris: "Electronics",
  },
  {
    vendorName: "TechTrends",
    owners: "Sophia Martinez",
    totalSales: "$9,200",
    product: 8,
    productsSold: 75,
    percentage: 33,
    rating: 4.2,
    status: "Inactive",
    categoris: "Sports",
  },
  {
    vendorName: "AppArena",
    owners: "Ethan Anderson",
    totalSales: "$11,800",
    product: 14,
    productsSold: 90,
    percentage: 42,
    rating: 4.5,
    status: "Active",
    categoris: "Books",
  },
  {
    vendorName: "Digital Den",
    owners: "Isabella Thomas",
    totalSales: "$14,100",
    percentage: 49,
    product: 20,
    productsSold: 115,
    rating: 4.7,
    status: "Active",
    categoris: "Toys",
  },
];

export const commissionData = [
  { month: "Jan", commission: 2400},
  { month: "Feb", commission: 4500 },
  { month: "Mar", commission: 1420 },
  { month: "Apr", commission: 2120 },
  { month: "May", commission: 3140 },
  { month: "Jun", commission: 9400 },
  { month: "Jul", commission: 9100 },
  { month: "Aug", commission: 6052 },
  { month: "Sept", commission:2765 },
  { month: "Oct", commission: 11000 },
  { month: "Nov", commission: 12000 },
  { month: "Dec", commission: 2800 },
];



export const database = [
  {
    vendor: "Innovation Inc",
    customer: "John Doe",
    email:"johndoe@gmail.com",
    products:2,
    total: "$250.00",
    status: "Suspended",
    payment:"paid",
    commission:"$66.70",
    orderDate: "2024-09-15",
    category:'Electronics',
  },
  {
    vendor: "Novel Nook",
    customer: "Jane Smith",
    email:"janesmith@gmail.com",
    products:2,
    total: "$913.00",
    status: "pending",
    payment:"pending",
    commission:"91.00",
    orderDate: "2024-09-15", category:'Automative',
  },
  {
    vendor: "Top Treasury",
    customer: "John Doe",
    email:"johndoe@gmail.com",
    products:4,
    total: "$2500.00",
    status: "Rejected",
    payment:"failed",
    commission:"$152.00",
    orderDate: "2024-09-15", category:'Fashion',
  },
  {
    vendor: "Car Care Plus",
    customer:"sam smith",
    email:"samsmith@gmail.com",
    products:2,
    total: "$5980.00",
    status: "Pending",
    payment:"pending",
    commission:"$161.00",
    orderDate: "2024-09-15", category:'Home & Garden',
  },
  {
    vendor: "Glamour Shop",
    customer:"alex john",
    email:"alexjohn@gmail.com",
    products:8,
    total: "$8500.00",
    status: "suspended",
    payment:"refunded",
    commission:"$162.00",
    orderDate: "2024-09-15", category:'Beauty',
  },
  {
    vendor: "Kiddie Kingdom",
    customer:"maria garcia",
    email:"mariagarcia@gmail.com",
    products:1,
    total: "$150.00",
    status: "Pending",
    payment:"paid",
    commission:"$169.00",
    orderDate: "2024-09-15", category:'Books',
  },
  {
    vendor: "Makeup Maven",
    customer:"linda brown",
    email:"lindabrown@gmail.com",
    products:3,
    total: "$750.00",
    status: "Rejected",
    payment:"failed",
    commission:"$220.90",
    orderDate: "2024-09-15", category:'Toys',
  },
  {
   vendor:"Skin Savvy",
    customer:"robert davis",
    email:"robertdavis@gmail.com",
    products:5,
    total: "$1250.00",
    status: "Rejected",
    payment:"paid",
    commission:"$174.40",
    orderDate: "2024-09-15", category:'Sports',
  },
  {
    vendor: "Wardrobe Wonders",
    customer: "John Doe",
    email:"johndoe@gmail.com",
    products:2,
    total: "$250.00",
    status: "Suspended",
    payment:"paid",
    commission:"$182.87",
    orderDate: "2024-09-15", category:'Software',
  },
  {
    vendor: "Fun Factory",
    customer: "Jane Smith",
    email:"janesmith@gmail.com",
    products:2,
    total: "$250.00",
    status: "Suspended",
    payment:"pending",
    commission:"$182.87",
    orderDate: "2024-09-15", category:'Electronics',
  },
  {
    vendor: "Garden Paradise",
    customer: "John Doe",
    email:"johndoe@gmail.com",
    products:4,
    total: "$2500.00",
    status: "Pending",
    payment:"failed",
    commission:"$182.87",
    orderDate: "2024-09-15", category:'Automative',
  },
  {
    vendor: "Beauty Bliss",
    customer:"sam smith",
    email:"samsmith@gmail.com",
    products:2,
    total: "$5980.00",
    status: "Rejected",
    payment:"pending",   
    commission:"$304.87",
    orderDate: "2024-09-15", category:'Toys',
  },
  {
    vendor: "Fitness First",
    customer:"alex john",
    email:"alexjohn@gmail.com",
    products:8,
    total: "$8500.00",
    status: "Pending",
    payment:"refunded",
    commission:"$89.87",
    orderDate: "2024-09-15",  category:'Books',
  },
  {
    vendor: "Chic Boutique",
    customer:"maria garcia",
    email:"mariagarcia@gmail.com",
    products:1,
    total: "$150.00",
    status: "Suspended",
    payment:"paid",
    commission:"$243.87",
    orderDate: "2024-09-15",  category:'Home & Garden',
  },
  {
    vendor: "Auto Parts Pro",
    customer:"linda brown",
    email:"lindabrown@gmail.com",
    products:3,
    total: "$750.00",
    status: "pending",
    payment:"failed",
    commission:"$82.87",
    orderDate: "2024-09-15", category:'Electronics',
  },
  {
   vendor:"Cosmetic Corner",
    customer:"robert davis",
    email:"robertdavis@gmail.com",
    products:5,
    total: "$1250.00",
    status: "Pending",
    payment:"paid",
    commission:"$382.87",
    orderDate: "2024-09-15", category:'Electronics',
  },
];