export const user_data= [
    {
      id: 1,
      name: "John Doe",
      email: "john@example.com",
      role: "Admin",
      status: "Active",
      verified: true,
      subscription: "Premium",
      location: "New York, USA",
      registered: "2024-01-15",
      lastActive: "2 hours ago",
      totalSpent: 1250,
      age: 32,
      gender: "Male",
      activityScore: 95,
    },
    {
      id: 2,
      name: "Sarah Smith",
      email: "sarah@example.com",
      role: "Manager",
      status: "Active",
      verified: true,
      subscription: "Premium",
      location: "London, UK",
      registered: "2024-02-20",
      lastActive: "5 hours ago",
      totalSpent: 890,
      age: 28,
      gender: "Female",
      activityScore: 88,
    },
    {
      id: 3,
      name: "Mike Johnson",
      email: "mike@example.com",
      role: "Customer",
      status: "Active",
      verified: false,
      subscription: "Free",
      location: "Toronto, Canada",
      registered: "2024-03-10",
      lastActive: "1 day ago",
      totalSpent: 450,
      age: 35,
      gender: "Male",
      activityScore: 72,
    },
    {
      id: 4,
      name: "Emily Davis",
      email: "emily@example.com",
      role: "Customer",
      status: "Inactive",
      verified: true,
      subscription: "Trial",
      location: "Sydney, Australia",
      registered: "2024-04-05",
      lastActive: "1 week ago",
      totalSpent: 120,
      age: 24,
      gender: "Female",
      activityScore: 45,
    },
    {
      id: 5,
      name: "David Wilson",
      email: "david@example.com",
      role: "Customer",
      status: "Banned",
      verified: true,
      subscription: "Free",
      location: "Berlin, Germany",
      registered: "2024-05-12",
      lastActive: "2 weeks ago",
      totalSpent: 0,
      age: 41,
      gender: "Male",
      activityScore: 12,
    },
    {
      id: 6,
      name: "Lisa Anderson",
      email: "lisa@example.com",
      role: "Manager",
      status: "Active",
      verified: true,
      subscription: "Premium",
      location: "Tokyo, Japan",
      registered: "2024-06-18",
      lastActive: "3 hours ago",
      totalSpent: 2100,
      age: 29,
      gender: "Female",
      activityScore: 92,
    },
    {
      id: 7,
      name: "Tom Brown",
      email: "tom@example.com",
      role: "Customer",
      status: "Active",
      verified: false,
      subscription: "Free",
      location: "Paris, France",
      registered: "2024-07-22",
      lastActive: "6 hours ago",
      totalSpent: 320,
      age: 38,
      gender: "Male",
      activityScore: 68,
    },
    {
      id: 8,
      name: "Anna Martinez",
      email: "anna@example.com",
      role: "Customer",
      status: "Active",
      verified: true,
      subscription: "Premium",
      location: "Madrid, Spain",
      registered: "2024-08-30",
      lastActive: "1 hour ago",
      totalSpent: 1540,
      age: 27,
      gender: "Female",
      activityScore: 85,
    },
  ];