export const UserData = [
    {
      id: 1,
      year: 2020,
      userGain: 80000,
      userLost: 823,
    },
    {
      id: 2,
      year: 2021,
      userGain: 70000,
      userLost: 345,
    },
    {
      id: 3,
      year: 2022,
      userGain: 78888,
      userLost: 555,
    },
    {
      id: 4,
      year: 2023,
      userGain: 60000,
      userLost: 4555,
    },
    {
      id: 5,
      year: 2024,
      userGain: 63000,
      userLost: 234,
    },
  ];

  export const topProductData = [
     {
      id : 1,
      productName : "Wireless Headphones Pro",
      quantity : 150,
      revenue : 15000,
    },
    {
      id : 2,
      productName : "Wireless Headphones Pro",
      quantity : 150,
      revenue : 15000,
    },
    {
      id : 3,
      productName : "Wireless Headphones Pro",
      quantity : 150,
      revenue : 15000,
    },
    {
      id : 4,
      productName : "Wireless Headphones Pro",
      quantity : 150,
      revenue : 15000,
    },
    {
      id : 5,
      productName : "Wireless Headphones Pro",
      quantity : 150,
      revenue : 15000,
    },
  ];

  export const recentActivityData = [
     {
      id : " ORD-1001 ",
      activity: " by William Smith ",
      icon: "🚚",
      status : "Shipped",
      time : "2 hours ago",
      payment:"$250.00",
     },
     {
      id : " ORD-1001 ",
      activity : " by Emily Johnson ",
      status : "Processing",
      icon: "⚙️",
      time : "2 hours ago",
      payment:"$250.00",
     },
     {
      id : " ORD-1001 ",
      activity : " by Michael Brown ",
      status : "Shipped",
      icon: "🚚",
      time : "2 hours ago",
      payment:"$250.00",
     },
     {
      id : " ORD-1001 ",
      activity : " by Olivia Davis ",
      status : "Shipped",
      icon: "🚚",
      time : "2 hours ago",
      payment:"$250.00",
     },
     {
      id : " ORD-1001 ",
      activity : " by James Wilson ",
      status : "Shipped",
      icon: "🚚",
      time : "2 hours ago",
      payment:"$250.00",
     },
  ];

 export const database = [
    {
      orderId: "ord-00135",
      customer: "John Doe",
      email:"johndoe@gmail.com",
      products:2,
      total: 250,
      status: "Pending",
      payment:"paid",
      orderDate: "2024-09-15",
    },
    {
      orderId: "ord-00115",
      customer: "Jane Smith",
      email:"janesmith@gmail.com",
      products:2,
      total: 250,
      status: "delivered",
      payment:"pending",
      orderDate: "2024-09-15",
    },
    {
      orderId: "ord-00015",
      customer: "John Doe",
      email:"johndoe@gmail.com",
      products:4,
      total: 2500,
      status: "processing",
      payment:"failed",
      orderDate: "2024-09-15",
    },
    {
      orderId: "ord-00005",
      customer:"sam smith",
      email:"samsmith@gmail.com",
      products:2,
      total: 5980,
      status: "delivered",
      payment:"pending",
      orderDate: "2024-09-15",
    },
    {
      orderId: "ord-00031",
      customer:"alex john",
      email:"alexjohn@gmail.com",
      products:8,
      total: 8500,
      status: "canceled",
      payment:"refunded",
      orderDate: "2024-09-15",
    },
    {
      orderId: "ord-00011",
      customer:"maria garcia",
      email:"mariagarcia@gmail.com",
      products:1,
      total: 150,
      status: "shipped",
      payment:"paid",
      orderDate: "2024-09-15",
    },
    {
      orderId: "ord-00091",
      customer:"linda brown",
      email:"lindabrown@gmail.com",
      products:3,
      total: 750,
      status: "pending",
      payment:"failed",
      orderDate: "2024-09-15",
    },
    {
     orderId:"ord-00081",
      customer:"robert davis",
      email:"robertdavis@gmail.com",
      products:5,
      total: 1250,
      status: "processing",
      payment:"paid",
      orderDate: "2024-09-15",
    },
    {
      orderId: "ord-00135",
      customer: "John Doe",
      email:"johndoe@gmail.com",
      products:2,
      total: 250,
      status: "Pending",
      payment:"paid",
      orderDate: "2024-09-15",
    },
    {
      orderId: "ord-00115",
      customer: "Jane Smith",
      email:"janesmith@gmail.com",
      products:2,
      total: 250,
      status: "delivered",
      payment:"pending",
      orderDate: "2024-09-15",
    },
    {
      orderId: "ord-00015",
      customer: "John Doe",
      email:"johndoe@gmail.com",
      products:4,
      total: 2500,
      status: "processing",
      payment:"failed",
      orderDate: "2024-09-15",
    },
    {
      orderId: "ord-00005",
      customer:"sam smith",
      email:"samsmith@gmail.com",
      products:2,
      total: 5980,
      status: "delivered",
      payment:"pending",
      orderDate: "2024-09-15",
    },
    {
      orderId: "ord-00031",
      customer:"alex john",
      email:"alexjohn@gmail.com",
      products:8,
      total: 8500,
      status: "canceled",
      payment:"refunded",
      orderDate: "2024-09-15",
    },
    {
      orderId: "ord-00011",
      customer:"maria garcia",
      email:"mariagarcia@gmail.com",
      products:1,
      total: 150.00,
      status: "shipped",
      payment:"paid",
      orderDate: "2024-09-15",
    },
    {
      orderId: "ord-00091",
      customer:"linda brown",
      email:"lindabrown@gmail.com",
      products:3,
      total: 750.,
      status: "pending",
      payment:"failed",
      orderDate: "2024-09-15",
    },
    {
     orderId:"ord-00081",
      customer:"robert davis",
      email:"robertdavis@gmail.com",
      products:5,
      total: 1250,
      status: "processing",
      payment:"paid",
      orderDate: "2024-09-15",
    },
  ];